name: RGSET
channels:
  - defaults
  - conda-forge
  - dglteam
  - pytorch
dependencies:
  - anaconda
  - python=3.6
  - pip=20.2.3
  - dgl-cuda11.0
  - pytorch-lightning=1.2.0
  - pytorch=1.7.1
  - pip:
      - -e .
      - -r file:requirements.txt
      - -r file:tests/requirements.txt
