name: RGSET
channels:
  - defaults
  - conda-forge
  - pytorch
  - dglteam
dependencies:
  - anaconda
  - python=3.6
  - pip=20.2.3
  - pytorch-lightning=1.1.8
  - pytorch
  - dgl-cuda11.0
#  - Install CUDA 10.1 version of DGL if on Lewis
#  - dgl-cuda10.1
  - pip:
      - -e .
      - -r file:requirements.txt
      - -r file:tests/requirements.txt
